using BO.Entities;
using DAL;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading;

namespace Tests.E2E;

/// <summary>
/// Shared WebApplicationFactory for quest E2E tests.
/// Replaces PostgreSQL with an isolated in-memory database and removes
/// background hosted services that require external dependencies.
/// </summary>
public class StreetFoodWebFactory : WebApplicationFactory<StreetFood.Program>
{
    // Unique DB per factory instance so parallel test classes don't collide.
    private readonly string _dbName = $"QuestE2E_{Guid.NewGuid()}";
    private int _seeded;
    private int _userIdSeed = 100;

    // 32-byte (256-bit) key used for both token generation and JWT validation override.
    private const string TestJwtKey = "StreetFoodE2ETestSecretKey123456";

    // ── Quest / Campaign IDs used across tests ────────────────────────────
    public const int CampaignId = 1;
    public const int QuestId = 1;
    public const int VisitTaskId = 1;   // VISIT  target=2
    public const int ReviewTaskId = 2;  // REVIEW target=1

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        // ConfigureTestServices runs AFTER Program.cs has registered its services,
        // so we can reliably remove and replace the PostgreSQL DbContext here.
        builder.ConfigureTestServices(services =>
        {
            // In EF Core 9, AddDbContext registers both DbContextOptions<T> AND an
            // internal IDbContextOptionsConfiguration<T> that carries the provider
            // configuration. We must remove ALL descriptors whose ServiceType is
            // generic with StreetFoodDbContext as the type argument (covers both
            // the options descriptor and the configuration descriptor), plus the
            // context itself.
            var dbContextType = typeof(StreetFoodDbContext);
            var toRemove = services
                .Where(d =>
                    d.ServiceType == dbContextType ||
                    d.ServiceType == typeof(DbContextOptions<StreetFoodDbContext>) ||
                    (d.ServiceType.IsGenericType &&
                     d.ServiceType.GenericTypeArguments.Length == 1 &&
                     d.ServiceType.GenericTypeArguments[0] == dbContextType))
                .ToList();
            foreach (var d in toRemove)
                services.Remove(d);

            services.AddDbContext<StreetFoodDbContext>(opts =>
                opts.UseInMemoryDatabase(_dbName));

            // Remove background hosted services (timers, cleanup jobs) that need
            // a real DB or external services at startup.
            var hostedServices = services
                .Where(d => d.ServiceType == typeof(IHostedService))
                .ToList();
            foreach (var hs in hostedServices)
                services.Remove(hs);

            // Override JWT validation to use the test key so tokens generated by
            // GenerateToken() are accepted by the middleware.
            var signingKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(TestJwtKey));
            services.PostConfigure<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme, opts =>
            {
                opts.TokenValidationParameters.IssuerSigningKey = signingKey;
                opts.TokenValidationParameters.ValidIssuer = "StreetFood";
                opts.TokenValidationParameters.ValidAudience = "StreetFoodUsers";
            });
        });
    }

    // ── Seed helpers ──────────────────────────────────────────────────────

    /// <summary>Seeds base read-only data (Tier, Campaign, Quest + Tasks). Idempotent.</summary>
    public void EnsureSeeded()
    {
        if (Interlocked.CompareExchange(ref _seeded, 1, 0) != 0)
            return;

        using var scope = Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<StreetFoodDbContext>();

        db.Tiers.Add(new Tier { TierId = 1, Name = "Basic", Weight = 1 });

        db.Campaigns.Add(new Campaign
        {
            CampaignId = CampaignId,
            Name = "Lễ Hội Ẩm Thực Hè 2026",
            Description = "Khám phá ẩm thực đường phố HCM",
            StartDate = DateTime.UtcNow.AddDays(-5),
            EndDate = DateTime.UtcNow.AddDays(30),
            IsActive = true,
            // Both vendor/branch FKs null → system campaign
        });

        db.Quests.Add(new Quest
        {
            QuestId = QuestId,
            Title = "Khám Phá Ẩm Thực Đường Phố HCM",
            Description = "Ghé thăm quán và viết đánh giá để nhận thưởng.",
            StartDate = DateTime.UtcNow.AddDays(-1),
            EndDate = DateTime.UtcNow.AddDays(30),
            IsActive = true,
            CampaignId = CampaignId,
            QuestTasks = new List<QuestTask>
            {
                new()
                {
                    QuestTaskId = VisitTaskId,
                    QuestId = QuestId,
                    Type = "VISIT",
                    TargetValue = 2,
                    Description = "Ghé thăm 2 quán ẩm thực trên app",
                    RewardType = "POINTS",
                    RewardValue = 50,
                },
                new()
                {
                    QuestTaskId = ReviewTaskId,
                    QuestId = QuestId,
                    Type = "REVIEW",
                    TargetValue = 1,
                    Description = "Viết 1 đánh giá chi tiết",
                    RewardType = "POINTS",
                    RewardValue = 30,
                },
            },
        });

        db.SaveChanges();
    }

    /// <summary>Adds a fresh User row. Returns the userId for use in tokens.</summary>
    public int SeedUser()
    {
        var userId = Interlocked.Increment(ref _userIdSeed);
        using var scope = Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<StreetFoodDbContext>();
        db.Users.Add(new User
        {
            Id = userId,
            Email = $"user{userId}@e2e.test",
            FirstName = "E2E",
            LastName = $"User{userId}",
            Role = Role.User,
            Point = 0,
        });
        db.SaveChanges();
        return userId;
    }

    // ── HTTP client helpers ───────────────────────────────────────────────

    public HttpClient CreateAuthClient(int userId, string role = "User")
    {
        var client = CreateClient();
        client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", GenerateToken(userId, role));
        return client;
    }

    private static string GenerateToken(int userId, string role)
    {
        // Use the test-specific key; JWT middleware is reconfigured in ConfigureWebHost
        // to accept tokens signed with this key (the production fallback key is too short).
        var key = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(TestJwtKey));
        var descriptor = new SecurityTokenDescriptor
        {
            Subject = new ClaimsIdentity(new[]
            {
                new Claim(ClaimTypes.NameIdentifier, userId.ToString()),
                new Claim(ClaimTypes.Role, role),
            }),
            Expires = DateTime.UtcNow.AddHours(1),
            Issuer = "StreetFood",
            Audience = "StreetFoodUsers",
            SigningCredentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256Signature),
        };
        var handler = new JwtSecurityTokenHandler();
        return handler.WriteToken(handler.CreateToken(descriptor));
    }
}
