// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using DAL;

namespace DAL.Migrations
{
    [DbContext(typeof(StreetFoodDbContext))]
    [Migration("20260215_AddMenuManagement")]
    partial class AddMenuManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Category
            modelBuilder.Entity("BO.Entities.Category", b =>
            {
                b.Property<int>("CategoryId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("category_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("description");

                b.Property<string>("ImageUrl")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("image_url");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("name");

                b.HasKey("CategoryId")
                    .HasName("pk_category");

                b.ToTable("category", (string)null);
            });

            // Taste
            modelBuilder.Entity("BO.Entities.Taste", b =>
            {
                b.Property<int>("TasteId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("taste_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TasteId"));

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("description");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("name");

                b.HasKey("TasteId")
                    .HasName("pk_taste");

                b.ToTable("taste", (string)null);
            });

            // Dish
            modelBuilder.Entity("BO.Entities.Dish", b =>
            {
                b.Property<int>("DishId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("dish_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DishId"));

                b.Property<int>("BranchId")
                    .HasColumnType("integer")
                    .HasColumnName("branch_id");

                b.Property<int>("CategoryId")
                    .HasColumnType("integer")
                    .HasColumnName("category_id");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("description");

                b.Property<string>("ImageUrl")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("image_url");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasColumnName("is_active")
                    .HasDefaultValue(true);

                b.Property<bool>("IsSoldOut")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasColumnName("is_sold_out")
                    .HasDefaultValue(false);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("name");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("price");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updated_at");

                b.HasKey("DishId")
                    .HasName("pk_dish");

                b.HasIndex("BranchId")
                    .HasDatabaseName("ix_dish_branch_id");

                b.HasIndex("CategoryId")
                    .HasDatabaseName("ix_dish_category_id");

                b.HasOne("BO.Entities.Branch", "Branch")
                    .WithMany()
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_dish_branch");

                b.HasOne("BO.Entities.Category", "Category")
                    .WithMany("Dishes")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_dish_category");

                b.ToTable("dish", (string)null);
            });

            // DishTaste
            modelBuilder.Entity("BO.Entities.DishTaste", b =>
            {
                b.Property<int>("DishTasteId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("dish_taste_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DishTasteId"));

                b.Property<int>("DishId")
                    .HasColumnType("integer")
                    .HasColumnName("dish_id");

                b.Property<int>("TasteId")
                    .HasColumnType("integer")
                    .HasColumnName("taste_id");

                b.HasKey("DishTasteId")
                    .HasName("pk_dish_taste");

                b.HasIndex("DishId")
                    .HasDatabaseName("ix_dish_taste_dish_id");

                b.HasIndex("TasteId")
                    .HasDatabaseName("ix_dish_taste_taste_id");

                b.HasOne("BO.Entities.Dish", "Dish")
                    .WithMany("DishTastes")
                    .HasForeignKey("DishId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_dish_taste_dish");

                b.HasOne("BO.Entities.Taste", "Taste")
                    .WithMany("DishTastes")
                    .HasForeignKey("TasteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_dish_taste_taste");

                b.ToTable("dish_taste", (string)null);
            });

            // DishDietaryPreference
            modelBuilder.Entity("BO.Entities.DishDietaryPreference", b =>
            {
                b.Property<int>("DishDietaryPreferenceId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("dish_dietary_preference_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DishDietaryPreferenceId"));

                b.Property<int>("DietaryPreferenceId")
                    .HasColumnType("integer")
                    .HasColumnName("dietary_preference_id");

                b.Property<int>("DishId")
                    .HasColumnType("integer")
                    .HasColumnName("dish_id");

                b.HasKey("DishDietaryPreferenceId")
                    .HasName("pk_dish_dietary_preference");

                b.HasIndex("DietaryPreferenceId")
                    .HasDatabaseName("ix_dish_dietary_preference_dietary_preference_id");

                b.HasIndex("DishId")
                    .HasDatabaseName("ix_dish_dietary_preference_dish_id");

                b.HasOne("BO.Entities.DietaryPreference", "DietaryPreference")
                    .WithMany("DishDietaryPreferences")
                    .HasForeignKey("DietaryPreferenceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_dish_dietary_preference_dietary");

                b.HasOne("BO.Entities.Dish", "Dish")
                    .WithMany("DishDietaryPreferences")
                    .HasForeignKey("DishId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_dish_dietary_preference_dish");

                b.ToTable("dish_dietary_preference", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
